src/Entity/LearningProgram.php
<?php

namespace App\Entity;

use App\Repository\LearningProgramRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LearningProgramRepository::class)
 */
class LearningProgram
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="learningPrograms")
     */
    private $student;

    /**
     * @ORM\ManyToMany(targetEntity=Lesson::class, inversedBy="learningPrograms")
     */
    private $lessons;

    public function __construct()
    {
        $this->lessons = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStudent(): ?User
    {
        return $this->student;
    }

    public function setStudent(?User $student): self
    {
        $this->student = $student;

        return $this;
    }

    /**
     * @return Collection|Lesson[]
     */
    public function getLessons(): Collection
    {
        return $this->lessons;
    }

    public function addLesson(Lesson $lesson): self
    {
        if (!$this->lessons->contains($lesson)) {
            $this->lessons[] = $lesson;
        }

        return $this;
    }

    public function removeLesson(Lesson $lesson): self
    {
        $this->lessons->removeElement($lesson);

        return $this;
    }
}

src/Entity/Lesson.php
<?php

namespace App\Entity;

use App\Repository\LessonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LessonRepository::class)
 */
class Lesson
{
    public const LESSON_TYPES = [
        'Прочее',
        'Сложные',
        'Лёгкие',
        'Дипломные',
        'Ознакомительные',
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $preview_description;

    /**
     * @ORM\Column(type="smallint")
     */
    private $type;

    /**
     * @ORM\ManyToMany(targetEntity=LearningProgram::class, mappedBy="lessons")
     */
    private $learningPrograms;

    public function __construct()
    {
        $this->learningPrograms = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getName() ?? '???';
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPreviewDescription(): ?string
    {
        return $this->preview_description;
    }

    public function setPreviewDescription(?string $preview_description): self
    {
        $this->preview_description = $preview_description;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getTypeName(): ?string
    {
        return self::LESSON_TYPES[$this->getType()] ?? null;
    }

    /**
     * @return Collection|LearningProgram[]
     */
    public function getLearningPrograms(): Collection
    {
        return $this->learningPrograms;
    }

    public function addLearningProgram(LearningProgram $learningProgram): self
    {
        if (!$this->learningPrograms->contains($learningProgram)) {
            $this->learningPrograms[] = $learningProgram;
            $learningProgram->addLesson($this);
        }

        return $this;
    }

    public function removeLearningProgram(LearningProgram $learningProgram): self
    {
        if ($this->learningPrograms->removeElement($learningProgram)) {
            $learningProgram->removeLesson($this);
        }

        return $this;
    }
}

src/Controller/LearningProgramController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class LearningProgramController extends AbstractController
{
    /**
     * @Route("/learning_program", name="app_learning_program")
     */
    public function index(): Response
    {
        return $this->render('learning_program/index.html.twig', [
            'controller_name' => 'LearningProgramController',
        ]);
    }
}

templates/learning_program/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% if not app.user.learningPrograms.toArray %}
        <p class="mt-4">Учебных программ не найдено</p>
    {% else %}
        <h4 class="mt-4">Учебные программы</h4>
        <div class="accordion mt-4" id="accordionLP">
            {% for learningProgram in app.user.learningPrograms %}
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingLP{{ learningProgram.id }}">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseLP{{ learningProgram.id }}" aria-expanded="false" aria-controls="collapseLP{{ learningProgram.id }}">
                            {{ learningProgram.name }}
                        </button>
                    </h2>
                    <div id="collapseLP{{ learningProgram.id }}" class="accordion-collapse collapse" aria-labelledby="headingLP{{ learningProgram.id }}" data-bs-parent="#accordionLP">
                        <div class="list-group list-group-flush">
                            {% for lesson in learningProgram.lessons %}
                                <a href="{{ path('app_lesson', {id: lesson.id}) }}" class="list-group-item list-group-item-action" aria-current="true">
                                    {{ lesson.name }}
                                    <span class="badge bg-info">{{ lesson.typeName }}</span>
                                    <div class="text-muted">{{ lesson.previewDescription }}</div>
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}